import {test} from 'node:test';
import assert from 'node:assert/strict';
import tls from 'node:tls';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {X509Certificate} from 'node:crypto';
import {createCodec8eServer,listenCodec8e} from './codec8e-server.mjs';
import {hello,simulatedFrame,SIM_IMEI} from './codec8e-simulator.mjs';
test('TLS requires trusted client certificate and pins it to device before persistence',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'geofield-tls-test-'));
 t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const keyPath=path.join(dir,'key.pem'),certPath=path.join(dir,'cert.pem');
 execFileSync(process.env.OPENSSL_BIN||'openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',keyPath,'-out',certPath,'-days','1','-subj','/CN=localhost','-addext','subjectAltName=DNS:localhost'],{stdio:'ignore'});
 const key=fs.readFileSync(keyPath),cert=fs.readFileSync(certPath),pin=new X509Certificate(cert).fingerprint256;let stored=0;
 const server=createCodec8eServer({devices:new Map([[SIM_IMEI,'device']]),serverFactory:cb=>tls.createServer({key,cert,ca:cert,requestCert:true,rejectUnauthorized:true,minVersion:'TLSv1.2'},cb),authorize:(s)=>s.authorized&&s.getPeerCertificate().fingerprint256===pin,persist:async()=>{stored++;return {status:'stored'};}});
 server.on('tlsClientError',()=>{});const port=await listenCodec8e(server);t.after(()=>server.close());
 const result=await new Promise((resolve,reject)=>{const s=tls.connect({port,host:'127.0.0.1',servername:'localhost',ca:cert,key,cert},()=>s.write(Buffer.concat([hello(),simulatedFrame()])));let b=Buffer.alloc(0);s.on('error',reject);s.on('data',c=>{b=Buffer.concat([b,c]);if(b.length>=5){s.destroy();resolve(b);}});s.setTimeout(3000,()=>{s.destroy();reject(Error('timeout'));});});
 assert.equal(result.toString('hex'),'0100000001');assert.equal(stored,1);
 await new Promise(resolve=>{const s=tls.connect({port,host:'127.0.0.1',servername:'localhost',ca:cert},()=>s.write(Buffer.concat([hello(),simulatedFrame()])));s.on('error',()=>{});s.on('close',resolve);s.setTimeout(3000,()=>s.destroy());});
 assert.equal(stored,1);
});
