-- AUTO-GENERATED PREREQ
-- Source migration: 20260208000400_preview_vft.sql
-- Purpose: avoid SQLSTATE 42P13 by dropping functions defined in source migration before it runs.
-- NOTE: Some signatures are skipped to avoid breaking column dependencies (DEFAULT/GENERATED).
begin;

drop function if exists public._col_exists(regclass, text);
drop function if exists public._col_exists(text, text);
drop function if exists public._email_norm(text);
drop function if exists public._geojson_extract_radius_m(jsonb);
drop function if exists public._geojson_to_multipolygon_4326(jsonb);
drop function if exists public._geom_from_geometry(jsonb);
drop function if exists public._is_root_claim();
drop function if exists public._memberships_role_type();
drop function if exists public._normalize_role_for_app_user_roles(uuid, uuid, text);
drop function if exists public._org_members_enforce_is_active_for_admins();
drop function if exists public._org_members_user_col();
drop function if exists public._org_parent_table_of_org_members();
drop function if exists public._organizations_plan_default_label();
drop function if exists public._pick_membership_role_label(text);
drop function if exists public._pick_org_table();
drop function if exists public._require_owner_or_admin(uuid);
drop function if exists public._resolve_tenant_for_current_user();
drop function if exists public._set_current_org_for_user(uuid, uuid);
drop function if exists public._user_has_org(uuid, uuid);
drop function if exists public.accept_invitation(uuid);
drop function if exists public.accept_invite_on_login();
drop function if exists public.accept_org_invites_for_current_user();
drop function if exists public.accept_pending_invite_for_current_user();
drop function if exists public.activities_create(text, text, boolean, text, numeric);
drop function if exists public.activities_delete(uuid);
drop function if exists public.activities_list(boolean);
drop function if exists public.activities_set_active(uuid, boolean);
drop function if exists public.activities_sync_org_tenant();
drop function if exists public.activities_update(uuid, text, text, text, numeric);
drop function if exists public.admin_assign_or_create_org(text, text);
drop function if exists public.admin_assign_role_org(text, text, uuid);
drop function if exists public.admin_assign_role_org(uuid, uuid, text);
drop function if exists public.admin_create_profile(text);
drop function if exists public.admin_debug_personal_lookup(uuid, uuid);
drop function if exists public.admin_delete_person(uuid);
drop function if exists public.admin_enroll_tracker(uuid, uuid, text, text);
drop function if exists public.admin_invite_new_admin(text, text);
drop function if exists public.admin_invite_new_admin(text, text, text);
drop function if exists public.admin_upsert_profile(uuid, uuid);
drop function if exists public.admin_upsert_tracker_assignment_v1(uuid, uuid, uuid, date, date, boolean);
drop function if exists public.admin_upsert_tracker_assignment_v2(uuid, uuid, uuid, uuid, date, date, boolean);
drop function if exists public.admins_list(uuid);
drop function if exists public.admins_remove(uuid, uuid);
drop function if exists public.api_register_event(uuid, double precision, double precision, timestamp with time zone);
drop function if exists public.app_admin_mode();
drop function if exists public.app_asignacion_set_estado(uuid, text);
drop function if exists public.app_asignacion_soft_delete(uuid);
drop function if exists public.app_asignacion_upsert(uuid, uuid, uuid, uuid, uuid, date, date, text, integer);
drop function if exists public.app_current_tenant_id(uuid);
drop function if exists public.app_ensure_org_and_membership(uuid, text, text);
drop function if exists public.app_install_rls(regclass, text, text, boolean);
drop function if exists public.app_is_admin(uuid);
drop function if exists public.app_is_member(uuid, text[]);
drop function if exists public.app_jwt_role();
drop function if exists public.app_jwt_tenant();
-- skipped: drop function if exists public.normalize_email(text);
-- skipped: drop function if exists public.normalize_phone(text);
drop function if exists public.app_personal_soft_delete(uuid);
drop function if exists public.app_set_tenant(uuid);
drop function if exists public.apply_invited_tracker_role();
drop function if exists public.apply_pending_invite_on_profile();
drop function if exists public.asignaciones_auto_estado();
drop function if exists public.asignaciones_check_tenant();
drop function if exists public.asignaciones_enforce_same_org();
drop function if exists public.asignaciones_enforce_tenant();
drop function if exists public.asignaciones_org_people_guard();
drop function if exists public.asignaciones_set_org_id();
drop function if exists public.assign_personal_to_geocerca(uuid, uuid, date, date, integer);
drop function if exists public.assign_personal_to_geocerca(uuid, uuid, uuid, date, date, integer);
drop function if exists public.audit_memberships();
drop function if exists public.audit_organizations();
drop function if exists public.bootstrap_session_context();
drop function if exists public.bootstrap_tracker_assignment_current_user(integer, integer);
drop function if exists public.bootstrap_user_after_login();
drop function if exists public.bootstrap_user_membership();
drop function if exists public.bootstrap_user_membership_for_user(uuid);
drop function if exists public.cancel_invitation(uuid);
drop function if exists public.claim_pending_invite(text);
drop function if exists public.compute_effective_app_role(uuid);
drop function if exists public.copy_tracker_log_to_positions();
drop function if exists public.count_active_trackers(uuid);
drop function if exists public.create_asignacion(uuid, uuid, date, date, integer);
drop function if exists public.create_asignacion(uuid, uuid, timestamp with time zone, timestamp with time zone, integer, text, text);
drop function if exists public.create_geocerca(text, jsonb);
drop function if exists public.create_organization(text, text);
drop function if exists public.create_organization_for_current_user(text);
drop function if exists public.create_personal_org_and_assign_owner();
drop function if exists public.current_geocerca_id_for_tracker(uuid);
drop function if exists public.current_org_id();
drop function if exists public.current_org_id_from_memberships();
drop function if exists public.current_role();
drop function if exists public.current_tenant_id();
drop function if exists public.current_user_email();
drop function if exists public.current_user_org_ids();
drop function if exists public.delete_all_geocercas_for_user();
drop function if exists public.delete_geofence_hard(uuid);
drop function if exists public.delete_user_full(uuid);
drop function if exists public.disable_assignments_when_geofence_inactive();
drop function if exists public.effective_tracker_limit(uuid);
drop function if exists public.enforce_geocercas_limit();
drop function if exists public.enforce_geocercas_total_limit();
drop function if exists public.enforce_geocercas_total_limit_core();
drop function if exists public.enforce_geocercas_total_limit_core_orig();
drop function if exists public.enforce_geocercas_total_limit_impl();
drop function if exists public.enforce_geofence_limit();
drop function if exists public.enforce_org_eq_tenant();
drop function if exists public.enforce_org_id();
drop function if exists public.enforce_org_people_tracker_limit();
drop function if exists public.enforce_owner_role();
drop function if exists public.enforce_personal_tracker_limit_final();
drop function if exists public.enforce_single_admin_invites();
drop function if exists public.enforce_single_admin_per_org();
drop function if exists public.enforce_tenant_id();
drop function if exists public.ensure_active_org_for_user(uuid);
drop function if exists public.ensure_admin_bootstrap(text);
drop function if exists public.ensure_current_org_for_user(uuid);
drop function if exists public.ensure_default_org();
drop function if exists public.ensure_default_org_for_current_user();
drop function if exists public.ensure_default_org_for_user(uuid);
drop function if exists public.ensure_geofence_from_geocerca(uuid);
drop function if exists public.ensure_membership_for_current_user();
drop function if exists public.ensure_membership_for_current_user(uuid, text);
drop function if exists public.ensure_membership_for_user(uuid);
drop function if exists public.ensure_org_for_admin_core(uuid, text, text);
drop function if exists public.ensure_org_for_admin_profile();
drop function if exists public.ensure_org_for_admin_profiles();
drop function if exists public.ensure_org_for_admin_user_profile();
drop function if exists public.ensure_org_for_current_user();
drop function if exists public.ensure_org_for_new_admin();
drop function if exists public.ensure_org_for_owner_role();
drop function if exists public.ensure_org_for_user();
drop function if exists public.ensure_owner_org_for_user(uuid, text);
drop function if exists public.ensure_personal_for_geocerca(uuid, uuid, text, text);
drop function if exists public.ensure_personal_for_user(uuid, uuid);
drop function if exists public.ensure_personal_org();
drop function if exists public.ensure_personal_org_for(uuid);
drop function if exists public.ensure_personal_org_for_user(uuid, text);
drop function if exists public.ensure_profile(uuid);
drop function if exists public.ensure_single_default_membership();
drop function if exists public.ensure_system_user_id();
drop function if exists public.ensure_tenant_for_org();
drop function if exists public.ensure_tracker_membership(text, uuid, text);
drop function if exists public.ensure_tracker_membership(uuid, text, uuid, text);
drop function if exists public.ensure_user_context();
drop function if exists public.ensure_user_membership(uuid, text);
drop function if exists public.ensure_user_org_context(uuid);
drop function if exists public.ensure_user_role(uuid, uuid, text);
drop function if exists public.ensure_user_tenant(uuid, text);
drop function if exists public.ensure_users_public_by_uid(uuid, text, text, uuid);
drop function if exists public.ensure_users_public_for_auth_user(uuid);
drop function if exists public.ensure_users_public_for_current_user(text, text, text);
drop function if exists public.f_admin_personal();
drop function if exists public.finish_asignacion(uuid, date);
drop function if exists public.fix_missing_membership_from_profile();
drop function if exists public.fn_normalize_phone_e164(text, text);
drop function if exists public.fn_normalize_phone_ec(text);
drop function if exists public.fn_personal_set_owner();
drop function if exists public.geocerca_get(text);
drop function if exists public.geocercas_bi_bu();
drop function if exists public.geocercas_bi_bu__orig();
drop function if exists public.geocercas_delete(uuid);
drop function if exists public.geocercas_delete_iof();
drop function if exists public.geocercas_enforce_canonical_fields();
drop function if exists public.geocercas_fix_org();
drop function if exists public.geocercas_insert_iof();
drop function if exists public.geocercas_list();
drop function if exists public.geocercas_set_geom();
drop function if exists public.geocercas_sync_nombre_name();
drop function if exists public.geocercas_update_iof();
drop function if exists public.geocercas_upsert(uuid, text, jsonb, boolean, boolean, text);
drop function if exists public.geocercas_v_delete();
drop function if exists public.geocercas_v_insert();
drop function if exists public.geocercas_v_update();
drop function if exists public.geofence_upsert(uuid, uuid, text, jsonb, boolean);
drop function if exists public.geofences_fill_user();
drop function if exists public.geofences_set_user_and_audit();
drop function if exists public.geofences_sync_geom_json();
drop function if exists public.geofences_sync_geometry();
drop function if exists public.geojson_to_coords(jsonb);
drop function if exists public.get_app_roots();
drop function if exists public.get_app_setting(text);
drop function if exists public.get_costos_asignaciones(timestamp with time zone, timestamp with time zone);
drop function if exists public.get_costos_asignaciones(timestamp with time zone, timestamp with time zone, uuid);
drop function if exists public.get_costos_asignaciones(date, date, uuid, uuid, uuid);
drop function if exists public.get_costos_asignaciones_v2(uuid, timestamp with time zone, timestamp with time zone);
drop function if exists public.get_costos_asignaciones_v2(date, date, uuid, uuid, uuid);
drop function if exists public.get_costos_detalle_by_org(uuid, timestamp with time zone, timestamp with time zone, uuid, uuid, uuid);
drop function if exists public.get_current_org();
drop function if exists public.get_current_org_id();
drop function if exists public.get_current_org_id_for_current_user();
drop function if exists public.get_current_org_id_for_user(uuid);
drop function if exists public.get_current_role(uuid);
drop function if exists public.get_current_user_org_and_role();
drop function if exists public.get_default_geofence_id(uuid);
drop function if exists public.get_default_org();
drop function if exists public.get_default_org_for_uid(uuid);
drop function if exists public.get_default_org_id_for_current_user();
drop function if exists public.get_geocercas_for_current_org();
drop function if exists public.get_geofence_context(uuid);
drop function if exists public.get_max_trackers_for_org(uuid);
drop function if exists public.get_my_context();
drop function if exists public.get_my_context_for_user(uuid);
drop function if exists public.get_my_profile();
drop function if exists public.get_or_create_default_org();
drop function if exists public.get_org_id_for_user(uuid);
drop function if exists public.get_org_limits(uuid);
drop function if exists public.get_owner_org_id(uuid);
drop function if exists public.get_request_user_id();
drop function if exists public.get_system_user_id();
drop function if exists public.get_tracker_invite_claim(uuid);
drop function if exists public.guard_profiles_direct_writes();
drop function if exists public.handle_new_admin_user();
drop function if exists public.has_role(uuid, public.role_type);
drop function if exists public.init_admin_tenant();
drop function if exists public.insert_geocerca(text, text);
drop function if exists public.insert_geocerca_json(text, jsonb);
drop function if exists public.insert_tracker_position(double precision, double precision, double precision, timestamp with time zone, text);
drop function if exists public.insert_tracker_position(double precision, double precision, double precision, timestamp with time zone, jsonb, uuid);
drop function if exists public.invite_member(uuid, text, public.role_type);
drop function if exists public.invite_member_by_email(uuid, text, public.role_type);
drop function if exists public.is_admin_context();
drop function if exists public.is_admin_or_owner(uuid);
drop function if exists public.is_admin_role(text);
drop function if exists public.is_admin_role(public.role_type);
drop function if exists public.is_app_root(uuid);
drop function if exists public.is_internal_bridge();
drop function if exists public.is_member(uuid);
drop function if exists public.is_member_of_org(uuid);
drop function if exists public.is_org_admin(uuid);
drop function if exists public.is_org_admin(uuid, uuid);
drop function if exists public.is_org_member(uuid);
drop function if exists public.is_org_owner(uuid, uuid);
drop function if exists public.is_owner();
drop function if exists public.is_root_owner();
drop function if exists public.is_root_owner(uuid);
drop function if exists public.is_tracker_assigned_to_geofence(uuid, uuid);
drop function if exists public.list_asignaciones(uuid, uuid, uuid, text);
drop function if exists public.list_geocercas_for_assign();
drop function if exists public.list_members_with_email(uuid);
drop function if exists public.log_event(text, text, uuid, jsonb);
drop function if exists public.log_location_and_attendance(double precision, double precision);
drop function if exists public.lower(public.role_type);
drop function if exists public.memberships_role_guard();
drop function if exists public.merge_personal_duplicates();
drop function if exists public.merge_to_tenant_by_name(regclass, text, text, text, uuid);
drop function if exists public.move_asignacion_dates(uuid, date, date);
drop function if exists public.move_asignacion_dates(uuid, timestamp with time zone, timestamp with time zone);
drop function if exists public.my_org_ids();
drop function if exists public.normalize_phone_for_personal(text);
drop function if exists public.on_org_invite_accepted();
drop function if exists public.on_organization_created();
drop function if exists public.personal_acl_probe(uuid);
drop function if exists public.personal_biu_defaults_v1();
drop function if exists public.personal_compute_fingerprint(text, text, text, text, uuid);
drop function if exists public.personal_delete_admin(uuid, uuid, uuid);
drop function if exists public.personal_has_active_assignments(uuid);
drop function if exists public.personal_list(text, boolean);
drop function if exists public.personal_list(text, boolean, integer);
drop function if exists public.personal_set_derived();
drop function if exists public.personal_set_vigente(uuid, boolean);
drop function if exists public.personal_soft_delete(uuid);
drop function if exists public.personal_toggle_admin(uuid, uuid, uuid);
drop function if exists public.personal_upsert_admin(uuid, uuid, jsonb);
drop function if exists public.pick_active_org_for_user(uuid);
drop function if exists public.prevent_membership_role_escalation();
drop function if exists public.prevent_past_asignaciones();
drop function if exists public.prevent_personal_duplicate_on_undelete();
drop function if exists public.prevent_role_change_for_non_admin();
drop function if exists public.process_geofence_transitions();
drop function if exists public.recalc_users_public_role_from_memberships();
drop function if exists public.remove_member(uuid, uuid);
drop function if exists public.repair_users_without_membership();
drop function if exists public.repair_users_without_roles();
drop function if exists public.resolve_auth_user_id_by_email(text);
drop function if exists public.resolve_geofence_id_from_geocerca(uuid);
drop function if exists public.resolve_tenant_id_for_org(uuid);
drop function if exists public.resolve_tracker_user_id(uuid);
drop function if exists public.role_id_to_role(uuid);
drop function if exists public.role_priority(text);
drop function if exists public.role_rank(text);
drop function if exists public.rpc_accept_invite(uuid);
drop function if exists public.rpc_accept_pending_invites_for_me();
drop function if exists public.rpc_admin_assign_geocerca(uuid, uuid);
drop function if exists public.rpc_admin_upsert_phone(uuid, text);
drop function if exists public.rpc_crear_geocerca(text, jsonb, boolean);
drop function if exists public.rpc_create_tracker_invite(uuid, text, integer, text);
drop function if exists public.rpc_personal_list(uuid);
drop function if exists public.rpc_plan_tracker_vigente_usage(uuid);
drop function if exists public.rpc_provision_tracker_and_assign(uuid, uuid, integer, boolean);
drop function if exists public.rpc_set_current_org(uuid);
drop function if exists public.rpc_tracker_can_send();
drop function if exists public.rpc_upsert_tracker_assignment(uuid, uuid, integer, boolean);
drop function if exists public.safe_add_to_publication(text, text, text);
drop function if exists public.safe_geom_from_geojson(jsonb);
drop function if exists public.session_org_id_safe();
drop function if exists public.set_active_org(uuid);
drop function if exists public.set_created_by();
drop function if exists public.set_created_by_from_auth();
drop function if exists public.set_current_org(uuid);
drop function if exists public.set_current_org_on_invite_accept();
drop function if exists public.set_current_org_on_membership_insert();
drop function if exists public.set_current_org_on_org_create();
drop function if exists public.set_default_org(uuid);
drop function if exists public.set_default_role_tracker();
drop function if exists public.set_geo_audit_fields_from_auth();
drop function if exists public.set_geocerca_org_defaults();
drop function if exists public.set_geofence_org();
drop function if exists public.set_member_role(uuid, uuid, public.role_type);
drop function if exists public.set_org_defaults();
drop function if exists public.set_org_owner_defaults();
drop function if exists public.set_owner_id();
drop function if exists public.set_owner_on_insert();
drop function if exists public.set_owner_on_insert_tbl();
drop function if exists public.set_personal_defaults();
drop function if exists public.set_updated_at();
drop function if exists public.set_user_role(uuid, uuid);
drop function if exists public.sync_app_user_roles_from_memberships();
drop function if exists public.sync_org_members_from_app_user_roles();
drop function if exists public.sync_org_tenant_from_geocercas();
drop function if exists public.sync_owner_membership_on_org_update();
drop function if exists public.sync_tracker_assignments_from_asignaciones(uuid);
drop function if exists public.sync_users_public_from_auth_users();
drop function if exists public.tg_col_exists(text, text);
drop function if exists public.tg_create_org_for_user(uuid, text);
drop function if exists public.tg_ensure_membership(uuid, uuid);
drop function if exists public.tg_ensure_owner_role();
drop function if exists public.tg_ensure_owner_role(uuid, uuid);
drop function if exists public.tg_get_profile_email(uuid);
drop function if exists public.tg_org_after_insert_ensure_owner_role();
drop function if exists public.tg_org_people_consistency();
drop function if exists public.tg_org_people_soft_delete_consistency();
drop function if exists public.tg_personal_phone_normalizer();
drop function if exists public.tg_pick_app_user_roles_conflict_constraint();
drop function if exists public.to_multipolygon_4326(public.geometry, double precision, double precision);
drop function if exists public.touch_updated_at();
drop function if exists public.tracker_assignment_create(uuid, uuid, uuid, timestamp with time zone, timestamp with time zone, integer, boolean);
drop function if exists public.tracker_assignment_set_window(uuid, timestamp with time zone, timestamp with time zone, integer, boolean);
drop function if exists public.tracker_assignments_defaults();
drop function if exists public.tracker_assignments_ensure_dates();
drop function if exists public.tracker_assignments_set_context();
drop function if exists public.tracker_assignments_sync_dates();
drop function if exists public.tracker_assignments_sync_period_tstz();
drop function if exists public.tracker_can_send();
drop function if exists public.tracker_can_send_details();
drop function if exists public.tracker_get_my_org();
drop function if exists public.tracker_get_org_for_user(uuid);
drop function if exists public.tracker_invites_set_is_active();
drop function if exists public.tracker_logs_set_geom();
drop function if exists public.tracker_logs_upsert_latest();
drop function if exists public.tracker_point_in_active_geocercas(uuid, text, double precision, double precision, timestamp with time zone);
drop function if exists public.tracker_positions_bi_set_geocerca();
drop function if exists public.tracker_self_provision(integer, integer);
drop function if exists public.trg_asignaciones_ensure_geofence_from_geocerca();
drop function if exists public.trg_asignaciones_sync_tracker_assignments();
drop function if exists public.trg_auth_users_ensure_membership();
drop function if exists public.trg_auth_users_ensure_tenant();
drop function if exists public.trg_fill_user_and_created();
drop function if exists public.trg_fill_user_only();
drop function if exists public.trg_geocercas_ensure_geofence();
drop function if exists public.trg_geocercas_force_org_id();
drop function if exists public.trg_geofences_set_org();
drop function if exists public.trg_geofences_set_org_orig();
drop function if exists public.trg_org_autojoin_owner();
drop function if exists public.trg_personal_bi_bu();
drop function if exists public.trg_personal_fill_fields();
drop function if exists public.trg_personal_set_org_owner();
drop function if exists public.trg_set_geocerca_id_on_tracker_positions();
drop function if exists public.trg_set_updated_at();
drop function if exists public.trg_sync_tracker_assignments_from_asignaciones();
drop function if exists public.trg_users_public_accept_invites();
drop function if exists public.trg_validate_tracker_assignment_geofence();
drop function if exists public.try_app_jwt_tenant_uuid();
drop function if exists public.update_geocerca(uuid, text, jsonb);
drop function if exists public.upsert_org_member(uuid, uuid, text);
drop function if exists public.upsert_personal(uuid, uuid, text, text, text, text, text, boolean, date, date);
drop function if exists public.upsert_tracker_assignment_auto(uuid, uuid, uuid, integer);
drop function if exists public.upsert_tracker_assignment_auto(uuid, text, integer, integer, boolean);
drop function if exists public.upsert_tracker_assignment_auto(uuid, text, text, integer, integer, boolean);
drop function if exists public.upsert_tracker_assignment_auto(uuid, uuid, uuid, integer, timestamp with time zone, timestamp with time zone);
drop function if exists public.upsert_tracker_assignment_by_email(uuid, text, uuid, integer, integer, boolean);
drop function if exists public.upsert_tracker_assignment_by_email(uuid, text, uuid, integer, timestamp with time zone, timestamp with time zone, boolean);
drop function if exists public.upsert_users_public_from_uid(uuid, text);

commit;

-- Skipped signatures count: 1