import React,{useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {authFetch} from '../lib/authFetch';
import {visitDrafts,putVisitDraft,acknowledgeVisit,deviceLocation,prepareVisitPhoto,csvCell} from '../lib/visitDrafts';
const words={
 es:{title:'Visitas',intro:'Módulo opcional. Cada persona decide cuándo documentar una visita.',enable:'Activar visitas para esta organización',disable:'Desactivar visitas',disabled:'Visitas está desactivado para esta organización.',start:'Iniciar visita',finish:'Finalizar visita',purpose:'Motivo de la visita',notes:'Notas',outcome:'Resultado',follow_up:'Pendientes',zone:'Geocerca',photo:'Adjuntar foto (JPG o PNG, máximo 2 MB)',photoHelp:'La ubicación corresponde al momento de adjuntar; no certifica dónde se tomó la foto.',located:'Ubicación informada por el dispositivo',noLocation:'Ubicación no disponible',save:'Guardar avances',pending:'Pendiente de sincronizar',synced:'Guardado',empty:'Todavía no hay visitas.',retry:'Actualizar / sincronizar',export:'Exportar CSV',search:'Filtrar por persona o geocerca',from:'Desde',to:'Hasta',history:'Historial (últimas 200 visitas)',viewPhoto:'Ver foto privada',error:'No se pudo sincronizar. Los registros pendientes se conservan en este dispositivo. Revisa tu conexión y sesión e inténtalo nuevamente.',loading:'Cargando…',photo_size:'Usa una foto JPG o PNG de hasta 2 MB.',select:'Selecciona una geocerca',open:'En curso',closed:'Finalizada',photoReady:'Foto preparada',minutes:'min',noZones:'No hay geocercas asignadas disponibles.',ready:'Guardado en este dispositivo; se sincronizará al tener conexión.',setup:'El módulo aún no está disponible. No se ha cambiado el seguimiento GPS.'},
 en:{title:'Visits',intro:'Optional module. Each person chooses when to document a visit.',enable:'Enable visits for this organization',disable:'Disable visits',disabled:'Visits is disabled for this organization.',start:'Start visit',finish:'Finish visit',purpose:'Visit purpose',notes:'Notes',outcome:'Outcome',follow_up:'Follow-up',zone:'Geofence',photo:'Attach photo (JPG or PNG, up to 2 MB)',photoHelp:'Location is captured when attaching; it does not certify where the photo was taken.',located:'Device-reported location',noLocation:'Location unavailable',save:'Save progress',pending:'Pending sync',synced:'Saved',empty:'No visits yet.',retry:'Refresh / sync',export:'Export CSV',search:'Filter by person or geofence',from:'From',to:'To',history:'History (latest 200 visits)',viewPhoto:'View private photo',error:'Sync failed. Pending records remain on this device. Check your connection and session, then retry.',loading:'Loading…',photo_size:'Use a JPG or PNG photo up to 2 MB.',select:'Select a geofence',open:'In progress',closed:'Completed',photoReady:'Photo ready',minutes:'min',noZones:'No assigned geofences available.',ready:'Saved on this device; will sync when connected.',setup:'This module is not available yet. GPS tracking is unchanged.'},
 fr:{title:'Visites',intro:'Module facultatif. Chaque personne choisit quand documenter une visite.',enable:'Activer les visites pour cette organisation',disable:'Désactiver les visites',disabled:'Les visites sont désactivées pour cette organisation.',start:'Commencer une visite',finish:'Terminer la visite',purpose:'Motif de la visite',notes:'Notes',outcome:'Résultat',follow_up:'À suivre',zone:'Géorepère',photo:'Joindre une photo (JPG ou PNG, 2 Mo maximum)',photoHelp:'La position est relevée lors de la pièce jointe ; elle ne certifie pas le lieu de prise de vue.',located:'Position déclarée par l’appareil',noLocation:'Position indisponible',save:'Enregistrer',pending:'Synchronisation en attente',synced:'Enregistré',empty:'Aucune visite.',retry:'Actualiser / synchroniser',export:'Exporter CSV',search:'Filtrer par personne ou géorepère',from:'Du',to:'Au',history:'Historique (200 dernières visites)',viewPhoto:'Voir la photo privée',error:'Échec de synchronisation. Les données restent sur cet appareil. Vérifiez la connexion et la session puis réessayez.',loading:'Chargement…',photo_size:'Utilisez une photo JPG ou PNG de 2 Mo maximum.',select:'Sélectionner un géorepère',open:'En cours',closed:'Terminée',photoReady:'Photo prête',minutes:'min',noZones:'Aucun géorepère attribué disponible.',ready:'Enregistré sur cet appareil ; sera synchronisé à la connexion.',setup:'Ce module n’est pas encore disponible. Le suivi GPS reste inchangé.'}
};
const box='w-full rounded-xl border border-slate-300 bg-white p-3 text-slate-900';
const button='rounded-xl bg-emerald-700 px-4 py-2 text-white disabled:opacity-50';
export default function VisitsPanel({orgId,runtime=null,identityUser=null}){
 const {i18n}=useTranslation(),w=words[i18n.language?.slice(0,2)]||words.es;
 const [data,setData]=useState(null),[drafts,setDrafts]=useState([]),[form,setForm]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[filter,setFilter]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const generation=useRef(0),running=useRef(false);
 const [initialPhoto,setInitialPhoto]=useState(null);
 const photoCopy={es:'Foto opcional del sitio, de los presentes o de un documento. Selecciona una imagen de tu dispositivo.',en:'Optional photo of the site, attendees or a document. Select an image from your device.',fr:'Photo facultative du site, des personnes présentes ou d’un document. Sélectionnez une image sur votre appareil.'};
 const scope=data?orgId+':'+data.user_id:null;
 async function api(body){
  const native = window.AndroidBridge || window.Android;
  if (runtime && native?.visitRequest) {
    return new Promise((resolve,reject)=>{
      const id=crypto.randomUUID();
      const done=event=>{if(event.detail?.id!==id)return;clearTimeout(timer);window.removeEventListener('geofield-visits-response',done);try{const result=JSON.parse(event.detail.body);if(event.detail.status>=400)reject(new Error(result.error));else resolve(result);}catch(error){reject(error);}};
      const timer=setTimeout(()=>{window.removeEventListener('geofield-visits-response',done);reject(new Error('timeout'));},45000);
      window.addEventListener('geofield-visits-response',done);
      native.visitRequest(id,JSON.stringify({org_id:orgId,user_id:runtime.trackerUserId,body:body||null}));
    });
  }
  const url='/api/visits' +(!body?'?org_id='+encodeURIComponent(orgId):'');
  const options=body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,org_id:orgId})}:{};
  let response;
  if(runtime){const token=localStorage.getItem('tracker_runtime_token')||runtime.runtimeToken;response=await fetch(url,{...options,headers:{...options.headers,Authorization:'Bearer '+token,'x-tracker-runtime':'1'}});}
  else response=await authFetch(url,options);
  const result=await response.json();if(!response.ok)throw new Error(result.error||'unavailable');return result;
 }
 async function load(){const gen=generation.current;try{const result=await api();if(gen!==generation.current)return;setData(result);localStorage.setItem('visits-context:'+orgId+':'+result.user_id,JSON.stringify({...result,visits:[]}));const list=await visitDrafts(orgId+':'+result.user_id);if(gen!==generation.current)return;setDrafts(list);setForm(current=>current||list.find(d=>!d.body.ended_at)?.body||result.visits.filter(v=>v.user_id===result.user_id&&!v.ended_at).map(v=>({...v,...v.document,photo:undefined,photo_ref:v.document.photo}))[0]||null);}catch{if(gen!==generation.current)return;const user=runtime?.trackerUserId||identityUser;try{const cached=JSON.parse(localStorage.getItem('visits-context:'+orgId+':'+user)||'null');if(cached&&user&&cached.user_id===user){setData(cached);const pending=await visitDrafts(orgId+':'+user);if(gen!==generation.current)return;setDrafts(pending);setForm(pending.find(d=>!d.body.ended_at)?.body||null);}}catch{}setMessage(w.error);}}
 async function flush(){if(!scope||running.current)return;running.current=true;const gen=generation.current;try{for(const d of await visitDrafts(scope)){if(gen!==generation.current)return;await api(d.body);await acknowledgeVisit(d);}if(gen===generation.current){setMessage('');await load();}}catch{if(gen===generation.current)setMessage(w.error);}finally{running.current=false;}}
 useEffect(()=>{generation.current++;setData(null);setForm(null);setInitialPhoto(null);setDrafts([]);setMessage('');load();return()=>{generation.current++;};},[orgId,runtime?.trackerUserId,identityUser]);
 useEffect(()=>{const online=()=>flush();window.addEventListener('online',online);const timer=setInterval(online,30000);return()=>{window.removeEventListener('online',online);clearInterval(timer);};},[scope,orgId]);
 async function save(finish=false){if(!form||!scope)return;setBusy(true);try{const body={...form,...(finish?{ended_at:new Date().toISOString(),end_location:await deviceLocation()}:{} )};await putVisitDraft(scope,body);setDrafts(await visitDrafts(scope));setForm(finish?null:body);setMessage(w.ready);await flush();}catch{setMessage(w.error);}finally{setBusy(false);}}
 async function start(e){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const body={id:crypto.randomUUID(),geofence_id:f.get('geofence'),assignment_id:data.assignments.find(a=>a.geofence_id===f.get('geofence'))?.id||null,started_at:new Date().toISOString(),purpose:f.get('purpose'),photo:initialPhoto||undefined,notes:'',outcome:'',follow_up:'',start_location:await deviceLocation()};await putVisitDraft(scope,body);setInitialPhoto(null);setForm(body);setDrafts(await visitDrafts(scope));await flush();}catch{setMessage(w.error);}finally{setBusy(false);}}
 async function configure(){setBusy(true);try{await api({action:'configure',enabled:!data.enabled});await load();}catch{setMessage(w.error);}finally{setBusy(false);}}
 const name=id=>{const p=data?.people.find(p=>p.user_id===id);return p?[p.nombre,p.apellido].filter(Boolean).join(' '):id;};
 const zone=id=>data?.geofences.find(g=>g.id===id)?.name||id;
 const rows=[...drafts.map(d=>({...d.body,document:d.body,user_id:data?.user_id,pending:true})),...(data?.visits||[]).filter(v=>!drafts.some(d=>d.body.id===v.id))].filter(v=>(name(v.user_id)+' '+zone(v.geofence_id)).toLowerCase().includes(filter.toLowerCase())&&(!from||v.started_at.slice(0,10)>=from)&&(!to||v.started_at.slice(0,10)<=to));
 function exportCsv(){const csv=[[w.zone,'Persona',w.from,w.to,w.purpose,w.notes,w.outcome,w.follow_up,'GPS inicio','GPS foto','Hora adjunto'] ,...rows.map(v=>[zone(v.geofence_id),name(v.user_id),v.started_at,v.ended_at,v.document.purpose,v.document.notes,v.document.outcome,v.document.follow_up,JSON.stringify(v.document.start_location),JSON.stringify(v.document.photo?.location),v.document.photo?.attached_at])].map(r=>r.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='visitas.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function photoPicker(photo){return <div className="space-y-2 rounded-xl border border-emerald-200 bg-emerald-50 p-4">
 <label className="block font-semibold">{w.photo}<input className={box} type="file" accept="image/jpeg,image/png" disabled={busy} onChange={async e=>{const input=e.currentTarget,file=input.files?.[0];if(!file)return;const gen=generation.current;setBusy(true);try{const selected=await prepareVisitPhoto(file);if(gen!==generation.current)return;if(form){const next={...form,photo:selected};await putVisitDraft(scope,next);if(gen!==generation.current)return;setForm(next);setDrafts(await visitDrafts(scope));}else setInitialPhoto(selected);setMessage(w.photoReady);}catch(err){if(gen===generation.current)setMessage(w[err.message]||w.error);}finally{input.value='';if(gen===generation.current)setBusy(false);}}}/></label>
 <p className="text-sm">{photoCopy[i18n.language?.slice(0,2)]||photoCopy.es}</p><p className="text-sm">{w.photoHelp}</p>
 {photo&&<><p>{w.photoReady} · {photo.location?w.located:w.noLocation}</p>{photo.base64&&<img className="max-h-60 max-w-full rounded-lg object-contain" src={'data:'+photo.type+';base64,'+photo.base64} alt={w.photoReady}/>}</>}
 </div>;}
 if(!orgId)return null;
 if(runtime&&!data)return null;
 if(runtime&&data&&!data.enabled&&!form&&!data.visits.length&&!drafts.length)return null;
 return <section className="mx-auto my-5 max-w-5xl space-y-5 rounded-2xl border border-emerald-100 bg-white p-5 text-left text-slate-900 shadow-sm">
 <h2 className="text-2xl font-bold">{w.title}</h2><p>{w.intro}</p>
 {message&&<p role="status" className="rounded-xl bg-amber-50 p-3 text-amber-900">{message}</p>}
 {!data?<p>{message?w.setup:w.loading}</p>:<>
 {data.manager&&<button className={button} disabled={busy} onClick={configure}>{data.enabled?w.disable:w.enable}</button>}
 {!data.enabled&&<p>{w.disabled}</p>}
 <button className="ml-2 underline" disabled={busy} onClick={async()=>{await load();await flush();}}>{w.retry}</button>
 {data.enabled&&!form&&<form onSubmit={start} className="space-y-3">
 <label className="block">{w.zone}<select name="geofence" className={box} required defaultValue=""><option value="">{w.select}</option>{data.geofences.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>
 {!data.geofences.length&&<p>{w.noZones}</p>}
 <label className="block">{w.purpose}<input name="purpose" className={box} required maxLength={200}/></label>{photoPicker(initialPhoto)}<button className={button} disabled={busy||!data.geofences.length}>{w.start}</button></form>}
 {form&&<div className="space-y-3 rounded-xl bg-emerald-50 p-4"><h3 className="font-bold">{w.open}: {zone(form.geofence_id)}</h3><p>{new Date(form.started_at).toLocaleString()} · {form.start_location?w.located:w.noLocation}</p>
 {['notes','outcome','follow_up'].map(k=><label className="block" key={k}>{w[k]}<textarea className={box} maxLength={k==='notes'?4000:2000} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}
 {photoPicker(form.photo||form.photo_ref)}
 <div className="flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={()=>save(false)}>{w.save}</button><button className={button} disabled={busy} onClick={()=>save(true)}>{w.finish}</button></div></div>}
 <h3 className="text-xl font-semibold">{w.history}</h3><div className="flex flex-wrap gap-2"><input aria-label={w.search} placeholder={w.search} className={box} value={filter} onChange={e=>setFilter(e.target.value)}/><label>{w.from}<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className={box}/></label><label>{w.to}<input type="date" value={to} onChange={e=>setTo(e.target.value)} className={box}/></label><button onClick={exportCsv} className={button}>{w.export}</button></div>
 {!rows.length&&<p>{w.empty}</p>}{rows.map(v=><article key={v.id} className="space-y-2 rounded-xl border p-4"><strong>{zone(v.geofence_id)} · {name(v.user_id)}</strong><p>{new Date(v.started_at).toLocaleString()} · {v.ended_at?`${w.closed} (${Math.round((Date.parse(v.ended_at)-Date.parse(v.started_at))/60000)} ${w.minutes})`:w.open} · {v.pending?w.pending:w.synced}</p><p>{v.document.purpose}</p>{['notes','outcome','follow_up'].map(k=>v.document[k]&&<p key={k}><b>{w[k]}: </b>{v.document[k]}</p>)}<p>{v.document.start_location?`${w.located}: ${v.document.start_location.lat}, ${v.document.start_location.lng} (±${Math.round(v.document.start_location.accuracy)} m)`:w.noLocation}</p>{v.document.photo&&<div><p>{w.photoHelp}</p><p>{new Date(v.document.photo.attached_at).toLocaleString()} · {v.document.photo.location?`${v.document.photo.location.lat}, ${v.document.photo.location.lng} (±${Math.round(v.document.photo.location.accuracy)} m)`:w.noLocation}</p>{v.photo_url&&<a href={v.photo_url} target="_blank" rel="noreferrer" className="underline">{w.viewPhoto}</a>}</div>}</article>)}
 </>}
 </section>;
}
